version: '3'
services: 
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: traffic-monitor-db
      POSTGRES_PASSWORD: <SUPER SECRET PASSWORD> 
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - traffic-monitor-network

  backend:
    build: ./backend
    image: traffic-monitor-backend
    networks:
      - traffic-monitor-network
    depends_on: 
      - db

networks:
  traffic-monitor-network:
    driver: bridge

volumes:
  dbdata: