spring:
  datasource:
    url: jdbc:postgresql://db:5432/traffic-monitor-db
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

google:
  maps:
    key: ${GOOGLE_MAPS_KEY}

locations:
  home: ${HOME_ADDRESS}
  work: ${WORK_ADDRESS}
